# Generated by Django 5.2.11 on 2026-02-24 19:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Título')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Datos adicionales de contexto para la conversación.', verbose_name='Contexto de la sesión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sesión de chat',
                'verbose_name_plural': 'Sesiones de chat',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente'), ('system', 'Sistema')], max_length=10, verbose_name='Rol')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.chatsession', verbose_name='Sesión')),
            ],
            options={
                'verbose_name': 'Mensaje de chat',
                'verbose_name_plural': 'Mensajes de chat',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_type', models.CharField(blank=True, default='', max_length=50, verbose_name='Tipo de habitación')),
                ('quality_score', models.FloatField(blank=True, help_text='Valor entre 0 y 10 indicando calidad de la imagen/espacio.', null=True, verbose_name='Puntuación de calidad')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción generada')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='Características detectadas')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Mensaje de error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('property_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='properties.propertyimage', verbose_name='Imagen de propiedad')),
            ],
            options={
                'verbose_name': 'Análisis de imagen',
                'verbose_name_plural': 'Análisis de imágenes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyValuation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estimated_price_xaf', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Precio estimado (XAF)')),
                ('confidence_score', models.FloatField(help_text='Valor entre 0 y 1 indicando confianza de la estimación.', verbose_name='Puntuación de confianza')),
                ('comparable_listings', models.JSONField(blank=True, default=list, help_text='IDs y precios de anuncios similares usados como referencia.', verbose_name='Anuncios comparables')),
                ('factors', models.JSONField(blank=True, default=dict, help_text='Factores que influyeron en el precio estimado.', verbose_name='Factores de valoración')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='properties.property', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Valoración de propiedad',
                'verbose_name_plural': 'Valoraciones de propiedades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(blank=True, default='', max_length=500, verbose_name='Consulta')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='Filtros aplicados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de búsqueda',
                'verbose_name_plural': 'Historial de búsquedas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(help_text='Valor entre 0 y 1 indicando relevancia para el usuario.', verbose_name='Puntuación de relevancia')),
                ('reason', models.TextField(blank=True, default='', help_text='Explicación de por qué se recomienda este anuncio.', verbose_name='Razón')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='listings.listing', verbose_name='Anuncio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Recomendación',
                'verbose_name_plural': 'Recomendaciones',
                'ordering': ['-score', '-created_at'],
                'unique_together': {('user', 'listing')},
            },
        ),
    ]
