# Generated by Django 5.2.11 on 2026-02-24 18:00

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalListing',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('operation_type', models.CharField(choices=[('venta', 'Venta'), ('alquiler', 'Alquiler'), ('alquiler_vacacional', 'Alquiler Vacacional')], max_length=25, verbose_name='Tipo de operación')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio')),
                ('currency', models.CharField(choices=[('XAF', 'Franco CFA'), ('EUR', 'Euro'), ('USD', 'Dólar')], default='XAF', max_length=3, verbose_name='Moneda')),
                ('price_xaf', models.DecimalField(decimal_places=2, help_text='Precio convertido a XAF para búsquedas normalizadas.', max_digits=12, verbose_name='Precio en XAF (normalizado)')),
                ('price_negotiable', models.BooleanField(default=False, verbose_name='Precio negociable')),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto de depósito')),
                ('deposit_currency', models.CharField(blank=True, max_length=3, null=True, verbose_name='Moneda del depósito')),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('pausado', 'Pausado'), ('vendido', 'Vendido'), ('alquilado', 'Alquilado'), ('expirado', 'Expirado')], default='activo', max_length=15, verbose_name='Estado')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('views_count', models.IntegerField(default=0, verbose_name='Vistas')),
                ('contacts_count', models.IntegerField(default=0, verbose_name='Contactos')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Creado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Publicado por')),
                ('property', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='properties.property', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'historical Anuncio',
                'verbose_name_plural': 'historical Anuncios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('venta', 'Venta'), ('alquiler', 'Alquiler'), ('alquiler_vacacional', 'Alquiler Vacacional')], max_length=25, verbose_name='Tipo de operación')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio')),
                ('currency', models.CharField(choices=[('XAF', 'Franco CFA'), ('EUR', 'Euro'), ('USD', 'Dólar')], default='XAF', max_length=3, verbose_name='Moneda')),
                ('price_xaf', models.DecimalField(decimal_places=2, help_text='Precio convertido a XAF para búsquedas normalizadas.', max_digits=12, verbose_name='Precio en XAF (normalizado)')),
                ('price_negotiable', models.BooleanField(default=False, verbose_name='Precio negociable')),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto de depósito')),
                ('deposit_currency', models.CharField(blank=True, max_length=3, null=True, verbose_name='Moneda del depósito')),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('pausado', 'Pausado'), ('vendido', 'Vendido'), ('alquilado', 'Alquilado'), ('expirado', 'Expirado')], default='activo', max_length=15, verbose_name='Estado')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('views_count', models.IntegerField(default=0, verbose_name='Vistas')),
                ('contacts_count', models.IntegerField(default=0, verbose_name='Contactos')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='Publicado por')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='properties.property', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='listings.listing', verbose_name='Anuncio')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'listing')},
            },
        ),
    ]
